apiVersion: v1
kind: Service
metadata:
    name: "ram-0e2e"
    labels:
        app: "ram-0e2e"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "ram-0e2e"